import java.util.Map;
import java.util.TreeMap;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LongNguyen
 */
public class frmNhaThue extends javax.swing.JFrame {

    DefaultTableModel model = null;
    public static Map<Integer, NhaThue> dsNT = new TreeMap<>();

    public static NhaThue nt = null;

    /**
     * Creates new form frmNhaThue
     */
    public frmNhaThue() {
        initComponents();
        model = (DefaultTableModel) tbDsNhaThue.getModel();
        txtMa.disable();

        NhaThue nt1 = new NhaThue(1, "nt1");
        nt1.themDS(new NguoiThue(1, "Long1", "123", "NT", "10-10-2010"));
        nt1.themDS(new NguoiThue(2, "Long2", "123", "NT", "10-10-2010"));
        nt1.themDS(new NguoiThue(3, "Long3", "123", "NT", "10-10-2010"));

        NhaThue nt2 = new NhaThue(2, "nt2");
        nt2.themDS(new NguoiThue(1, "LongVip1", "123", "NT", "10-10-2010"));
        nt2.themDS(new NguoiThue(2, "LongVip2", "123", "NT", "10-10-2010"));
        nt2.themDS(new NguoiThue(3, "LongVip3", "123", "NT", "10-10-2010"));

        NhaThue nt3 = new NhaThue(3, "nt3");
        nt3.themDS(new NguoiThue(1, "LongPro1", "123", "NT", "10-10-2010"));
        nt3.themDS(new NguoiThue(2, "LongPro2", "123", "NT", "10-10-2010"));
        nt3.themDS(new NguoiThue(3, "LongPro3", "123", "NT", "10-10-2010"));

        dsNT.put(1, nt1);
        dsNT.put(2, nt2);
        dsNT.put(3, nt3);

        capNhat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDsNhaThue = new javax.swing.JTable();
        btnQuanLy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUAN LY NHA THUE");

        jLabel2.setText("Ma");

        jLabel3.setText("Ten");

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cap nhat");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        tbDsNhaThue.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Ma", "Ten"
                }));
        tbDsNhaThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDsNhaThueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDsNhaThue);

        btnQuanLy.setText("Quan ly");
        btnQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 69,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtTen))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnQuanLy)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(btnThem)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(btnXoa)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(btnCapNhat))
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 375,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 5, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnThem)
                                        .addComponent(btnXoa)
                                        .addComponent(btnCapNhat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29,
                                        Short.MAX_VALUE)
                                .addComponent(btnQuanLy)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void capNhat() {
        model.setRowCount(0);
        for (NhaThue nt : dsNT.values()) {
            model.addRow(new Object[] { nt.getMa(), nt.getTen() });
        }
    }

    public void reset() {
        txtMa.setText("");
        txtTen.setText("");
    }

    public void setInput(NhaThue nt) {
        txtMa.setText(String.valueOf(nt.getMa()));
        txtTen.setText(nt.getTen());
    }

    public int checkMaThieu() {
        for (int i = 1; i <= dsNT.size(); i++) {
            if (dsNT.get(i) == null)
                return i;
        }

        return dsNT.size() + 1;
    }

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed
        int ma = checkMaThieu();
        dsNT.put(ma, new NhaThue(ma, txtTen.getText()));
        reset();
        capNhat();
    }// GEN-LAST:event_btnThemActionPerformed

    private void tbDsNhaThueMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tbDsNhaThueMouseClicked
        int index = tbDsNhaThue.getSelectedRow();
        int ma = Integer.parseInt(tbDsNhaThue.getValueAt(index, 0).toString());

        if (index >= 0) {
            setInput(dsNT.get(ma));
        }
    }// GEN-LAST:event_tbDsNhaThueMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
        int index = tbDsNhaThue.getSelectedRow();
        int ma = Integer.parseInt(tbDsNhaThue.getValueAt(index, 0).toString());

        if (index >= 0) {
            dsNT.remove(ma);
            reset();
            capNhat();
        }
    }// GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCapNhatActionPerformed
        int index = tbDsNhaThue.getSelectedRow();
        int ma = Integer.parseInt(tbDsNhaThue.getValueAt(index, 0).toString());

        if (index >= 0) {
            dsNT.get(ma).setTen(txtTen.getText());
            reset();
            capNhat();
        }
    }// GEN-LAST:event_btnCapNhatActionPerformed

    private void btnQuanLyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuanLyActionPerformed
        int index = tbDsNhaThue.getSelectedRow();
        int ma = Integer.parseInt(tbDsNhaThue.getValueAt(index, 0).toString());

        if (index >= 0) {
            nt = dsNT.get(ma);
            frmNguoiThue fnt = new frmNguoiThue();
            fnt.setVisible(true);
            fnt.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        }
    }// GEN-LAST:event_btnQuanLyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhaThue.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhaThue.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhaThue.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhaThue.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhaThue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnQuanLy;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDsNhaThue;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
